# Generated by Django 5.0.6 on 2024-06-02 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InitConds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('grid', models.CharField()),
                ('exe', models.CharField()),
                ('path', models.CharField()),
                ('preset', models.CharField()),
                ('log', models.TextField()),
            ],
            options={
                'db_table': 'init_conds',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Calculations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField()),
                ('init_cond', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.initconds')),
            ],
            options={
                'db_table': 'calculations',
                'managed': True,
            },
        ),
    ]
