# Generated by Django 5.0.6 on 2024-06-05 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculations',
            name='path',
        ),
        migrations.RemoveField(
            model_name='initconds',
            name='path',
        ),
        migrations.AddField(
            model_name='calculations',
            name='data_to_load',
            field=models.CharField(default=''),
        ),
        migrations.AddField(
            model_name='calculations',
            name='date',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='calculations',
            name='extract_step',
            field=models.CharField(default=''),
        ),
        migrations.AddField(
            model_name='calculations',
            name='ion_step',
            field=models.CharField(default=''),
        ),
        migrations.AddField(
            model_name='calculations',
            name='thermo_step',
            field=models.CharField(default=''),
        ),
        migrations.AddField(
            model_name='calculations',
            name='thermo_type',
            field=models.CharField(default=''),
        ),
    ]
