# Generated by Django 5.0.6 on 2024-06-09 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_calculations_path_remove_initconds_path_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='initconds',
            name='preset',
        ),
        migrations.AlterField(
            model_name='calculations',
            name='data_to_load',
            field=models.CharField(default=None),
        ),
        migrations.AlterField(
            model_name='calculations',
            name='extract_step',
            field=models.CharField(default=None),
        ),
        migrations.AlterField(
            model_name='calculations',
            name='ion_step',
            field=models.CharField(default=None),
        ),
        migrations.AlterField(
            model_name='calculations',
            name='thermo_step',
            field=models.CharField(default=None),
        ),
        migrations.AlterField(
            model_name='calculations',
            name='thermo_type',
            field=models.CharField(default=None),
        ),
        migrations.AlterField(
            model_name='initconds',
            name='date',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='initconds',
            name='exe',
            field=models.CharField(default=None),
        ),
        migrations.AlterField(
            model_name='initconds',
            name='grid',
            field=models.CharField(default=None),
        ),
        migrations.AlterField(
            model_name='initconds',
            name='log',
            field=models.TextField(default=None),
        ),
    ]
