# Generated by Django 5.0.6 on 2024-06-12 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_initconds_preset_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initconds',
            name='log',
            field=models.TextField(default=''),
        ),
    ]
