# Generated by Django 5.0.6 on 2024-06-17 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_initconds_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculations',
            name='log',
            field=models.TextField(default=''),
        ),
    ]
