# Generated by Django 5.0.6 on 2024-06-20 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_calculations_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculations',
            name='date',
            field=models.DateField(default='2014-01-01'),
        ),
    ]
